# 项目名
server:
  servlet:
    context-path: /httpDataApiByMybatis
    application-display-name: httpDataApiByMybatis
# spring配置
spring:
  profiles:
    active: dev
  main:
    banner-mode: console
  output:
    ansi:
      enabled: detect
  # devtools config
  devtools:
       restart:
         enabled: false
# http配置，编码格式utf-8 HttpMessageConverter换为 Gson 速度稍慢但是稳定
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
    converters:
      preferred-json-mapper: gson
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
# mybatis config
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
# logging config
logging:
  register-shutdown-hook: true
  folderPath: /logGroup/httpDataApiByMybatisLog/
  config: classpath:config/logback-spring.xml


